# fly.toml app configuration file generated for aeksion on 2023-08-23T16:02:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gramoladisco"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/rails/bin/rails console"

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = "bin/rails fly:release"

[env]
  LANG = "en_US.UTF-8"
  PORT = "3000"
  RACK_ENV = "production"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "disabled"
  RAILS_SERVE_STATIC_FILES = "enabled"

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ["web", "worker"]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
