# Patterns of URL to be considered malicious
patterns:
  - ^/wp-admin
  - ^/wp-login\.php$
  - ^/wp-includes/.*$
  - ^/wp-content/.*$
  - ^/wp-content/plugins/.*$
  - ^/wp-content/themes/.*$
  - ^/wp-content/uploads/.*$
  - ^/wp-content/cache/.*$
  - ^/wp-content/languages/.*$
  - ^/wp-content/upgrade/.*$
  - ^/wp-content/backup-db/.*$
  - ^/phpmyadmin$
  - ^/xmlrpc\.php$
  - ^/api/.*$
  - ^/admin\.php$
  - ^/galeria/.*$
  - ^/gallery/.*$
  - ^/login\.php$
  - ^/login$
  - ^/administrator$
  - ^/contacto
  - ^/dashboard$
  - ^/cgi-bin/.*$
  - ^/webdav/.*$
  - ^/ALFA_DATA/$
  - ^/.git.*$
  - ^/git.*$
  - ^/config/.*$
  - ^/database/.*$
  - ^/tmp/.*$
  - ^/vendor/.*$
  - ^/log/.*$
  - ^/public/system/.*$

# Keywords in URL (case-insensitive)
keywords:
  - 'wp\w*'
  - 'php.*'
  - 'perl.*'
  - 'alfa.*'
  - 'git'
  - 'svn'
  - 'hg'
  - 'cvs'
  - 'ssh'
  - 'sql'
  - 'php'
  - 'perl'
  - 'bash'
  - 'cmd'

# Error codes to not consider for blocking (optional)
error_codes:
  - 401
  - 403
  - 404

