default: &default
  host: <%= `ip route | awk '/default/ { print $3 }'`.strip %>
  port: 5432
  user: <%= Rails.application.credentials.dig(:DB_USER) %>
  password: <%= Rails.application.credentials.dig(:DB_PASSWORD) %>
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gramola_development

test:
  <<: *default
  database: gramola_test
